version: '3.9'

services:
  # dictionary
  cityinfo-db:
    image: "mysql"
    environment: 
    # list: 
    - MYSQL_ROOT_PASSWORD=dbadmin-pass
    - MYSQL_USER=dbadmin
    - MYSQL_PASSWORD=dbadmin-pass
    - MYSQL_DATABASE=cityinfo
    expose:
    - 3306
    networks:
    - backend

  events:
    build: Events
    environment: 
    - DB_HOST=cityinfo-db
    - DB_USER=dbadmin
    - DB_PASSWORD=dbadmin-pass
    - DB_NAME=cityinfo
    - HOST=0.0.0.0
    - PORT=5001
    # ports: # comunicare si din exterior
    # - 5001:5000
    expose:
    - 5000
    networks:
    - backend
    depends_on:
    - cityinfo-db

  redis-weather:
    image: redis
    networks:
    - backend

  weather:
    build: RedisWeather
    environment: 
    - REDIS_HOST=redis-weather
    expose: # comunicare doar din interior
    - 5000
    networks:
    - backend
    depends_on:
      - redis-weather

  # weather:
  #   build: Weather
  #   environment: 
  #   - DB_HOST=cityinfo-db
  #   - DB_USER=dbadmin
  #   - DB_PASSWORD=dbadmin-pass
  #   - DB_NAME=cityinfo
  #   - HOST=0.0.0.0
  #   - PORT=5002
  #   ports:
  #   - 5002:5002
  #   networks:
  #   - backend
  #   depends_on:
  #   - cityinfo-db

  gateway:
    build: Gateway
    environment: 
    - DB_HOST=cityinfo-db
    - DB_USER=dbadmin
    - DB_PASSWORD=dbadmin-pass
    - DB_NAME=cityinfo
    - HOST=0.0.0.0
    - PORT=5000
    - EVENT_SERVICE_URL=http://events:5000/events #5000 e cel din interior
    - WEATHER_SERVICE_URL=http://weather:5000/weather
    ports:
    - 8080:5000 # exterior:interior
    networks:
    - backend
    depends_on:
    - weather
    - events
      
networks:
  backend:
    driver: bridge
    name: backend-network